
export const experiences = [
    {
    company: "Chipotle",
    title: "Team Member",
    // team: "",
    period: "Sep 2025 - Present",
    description: "Collaborated with team members in a fast-paced environment to prepare and serve food while ensuring quality and consistency. Delivered excellent customer service, maintained cleanliness and food safety standards, and adapted quickly to changing priorities during peak hours.",
    icon: "/Images/favicon.svg",
    skills: [
      "Teamwork",
      "Customer Service",
      "Time Management",
      "Adaptability",
      "Attention to Detail",
      "Communication",
      "Conflict Resolution",
    ],
  },
  {
    company: "US Signal",
    title: "NOC Technician",
    // team: "",
    period: "Sep 2024 - Dec 2024",
    description: "Responsible for monitoring and responding to network backbone alarms for switches, routers, and Cisco Transport Units, as well as handling change management.",
    icon: "/Images/favicon.svg",
    skills: [
      "Alarm Monitoring",
      "Troubleshooting",
      "Documentation",
      "OSPF",
      "Customer Service",
      "Cisco Transport Controller",
      "Salesforce",
      "Open NMS",
      "DWDM",
    ],
  },
  {
    company: "University of Michigan - Dearborn",
    title: "Lead Developer - Senior Project",
    // team: "School Senior Project",
    period: "Sep 2022 - Dec 2022",
    description: "Led a team to work on legacy internal site Translation Networks with University of Michigan Dearborn professors as the clients with their use cases respectfully. Made major improvements to bring the site in line with WCAG 2 standards.",
    icon: "/Images/favicon.svg",
    skills: [
      "Javascript",
      "UML Diagrams",
      "ADA Complicance",
      "Scrum",
      "HTML",
      "CSS",
      "Management",
    ],
  },
  {
    company: "Freelance",
    title: "Competitive Gaming Coach",
    // team: "",
    period: "2019-2024",
    description: "Provided one-on-one coaching for competitive games such as League of Legends, Mordhau, and Street Fighter. Developed personalized improvement plans, analyzed gameplay footage, and guided clients in problem-solving and decision-making under pressure. Helped clients set and achieve measurable goals while fostering long-term improvement and confidence. Most importantly, strived to shape their mentality around calmness and an improvement mindset.",
    icon: "/Images/favicon.svg",
    skills: [
      "Communication",
      "Problem Solving",
      "Goal Setting",
      "Mentorship",
      "Performance Analysis",
      "Adaptability",
      "Critical Thinking",
      "Conflict Resolution",
    ],
  },
];